# Jekyll workshop-template https://github.com/evanwill/workshop-template
# based on minima theme https://github.com/jekyll/minima

title: GitHub Static website hosting
description: > 
  Learn about GitHub pages and Jekyll. 
keywords: "github, github-pages, websites, static gen, hosting, html, gh-pages"

url: "https://github.com/InikiMedia/github-static-hosting-presentation/" 

# author settings for cc-by
author: evan will
github_username: evanwill
pub_year: 2017
repo: "https://github.com/evanwill/go-go-ghpages"

google_analytics:

# Build settings
markdown: kramdown

# figure include: {% include image.html file="cat.jpg" alt="kitten" cap="My cat" width="45%" %}
